USE CodeAnalysis;
GO

CREATE TABLE LITERAL (
    LITERAL_ID INTEGER PRIMARY KEY,
    LITERAL VARCHAR(1000) NOT NULL
);

CREATE TABLE LITERAL_LOCATION (
    LITERAL_ID INTEGER NOT NULL,
    SOURCE_FILE_ID INTEGER NOT NULL,
    LINE INTEGER NOT NULL,
    CHARACTER INTEGER NOT NULL,
    IS_CONSTANT BIT NOT NULL,
    PRIMARY KEY (LITERAL_ID, SOURCE_FILE_ID, LINE, CHARACTER),
    FOREIGN KEY (LITERAL_ID) REFERENCES LITERAL (LITERAL_ID)
);

CREATE TABLE dbo.SOURCE_FILE (
    SOURCE_FILE_ID INTEGER IDENTITY PRIMARY KEY,
    FILE_NAME VARCHAR(1000) NOT NULL
);
